collections_config:
  pages:
    output: true
    url: "/content/[slug]"
    add_options:
      - name: Add Page
        href: "cloudcannon:explore/content/.mdðŸ†•/content/schemas/pages.md"
  blog:
    output: true
    url: "/content/blog/[slug]"
    add_options:
      - name: Add Page
        href: "cloudcannon:explore/content/blog/.mdðŸ†•/content/schemas/blog.md"
collection_groups:
  - heading: Profile and Settings
    collections:
      - data
  - heading: Pages
    collections:
      - pages
      - podcasts
      - legal
      - contact
      - thank-you
_inputs:
  date:
    type: date
  categories:
    type: array